title: "EST"
description: "Repositório para disciplinas de Estatística e Probabilidades da UFMG"
baseurl: "/EST"
url: "https://urielmoreirasilva.github.io"
remote_theme: just-the-docs/just-the-docs
